### PR TITLE
Dickey2

### PR DESCRIPTION
**Pull request by ThomasDickey**

### CODE REVIEW

**Comment by gnachman** [comment]
I thought the mixup of the DECRQCRA args was fixed in patch 315? Your original change to the readme in commit 2b694588 changed it to say:

```
--disable-xterm-checksum-bug
xterm's implementation of DECRQCRA (fixed in patch 315, early 2015) contained a
bug.  DECRQCRA is essential to these tests.  By default, a workaround for the
bug is used in case an old version of xterm is tested.
```

**Comment by ThomasDickey** [comment]
sure - I changed the wording to indicate when it was fixed, but didn't change the logic.  It's a double-negative, so if you remove the test, you still need the assignment.

**Comment by gnachman** [comment]
The spec for DECRQCRA defines it as:

```
CSI Pid ; Pp ; Pt ; Pl ; Pb ; Pr * y
```

The code with this PR will send `Pp` first and `Pid` second only for xterm. That was necessary when xterm had those values swapped, but should not be needed any longer.

Since the value of `Pp` passed to `esccmd.DECRQCRA` is always 0, things will appear to work until an exception is raised after sending `DECRQCRA` and the `Pid` becomes needed to ignore a response code that a subsequent test should ignore.

**Comment by ThomasDickey** [comment]
I see the problem now: shortly after applying the fix you sent, I noticed the same issue with DECCKSR, and (incorrectly) undid your fix.  So... the option is still needed :-(

**Comment by ThomasDickey** [comment]
I see the problem now: shortly after applying the fix you sent, I noticed the same issue with DECCKSR, and (incorrectly) undid your fix.  So... the option is still needed :-(

**Comment by ThomasDickey** [comment]
I'll make an update which detects the xterm patch number to handle the special case, in the next day or so.

**Comment by gnachman** [comment]
I'll merge this since it will fix the tests for now, and just send another PR once the patch is in. I'd rather not keep the flag around since it adds needless complexity; anyone who is running these tests should use the latest code of whatever terminal they're testing.

**Pull request merged**
